export type Language = 'ru' | 'en';

export const STRINGS = {
  'nav.home': { ru: 'Ссылка', en: 'Link' },
  'nav.inbox': { ru: 'Входящие', en: 'Inbox' },
  'nav.settings': { ru: 'Настройки', en: 'Settings' },
  'nav.sections': { ru: 'Разделы', en: 'Sections' },

  'common.back': { ru: 'Назад', en: 'Back' },
  'common.retry': { ru: 'Ещё раз', en: 'Try again' },
  'common.save': { ru: 'Сохранить', en: 'Save' },
  'common.saved': { ru: 'Сохранено', en: 'Saved' },

  'error.title': { ru: 'Не получилось', en: "That didn't work" },
  'error.generic': { ru: 'Что-то сломалось на нашей стороне. Попробуй чуть позже', en: 'Something broke on our side. Try again a bit later' },
  'error.offline': { ru: 'Нет связи с сервером. Проверь интернет', en: "Can't reach the server. Check your connection" },
  'error.reopen': { ru: 'Открой приложение заново из чата с ботом', en: 'Reopen the app from the bot chat' },
  'error.outside.title': { ru: 'Открой в Telegram', en: 'Open in Telegram' },
  'error.outside.note': { ru: 'Анонка работает внутри Telegram. Найди бота и нажми «Открыть анонку»', en: 'Anonka lives inside Telegram. Find the bot and tap Open Anonka' },

  'time.now': { ru: 'только что', en: 'just now' },
  'time.minutes': { ru: '{n} мин назад', en: '{n} min ago' },
  'time.hours': { ru: '{n} ч назад', en: '{n} h ago' },

  'word.visit1': { ru: 'переход', en: 'visit' },
  'word.visit2': { ru: 'перехода', en: 'visits' },
  'word.visit5': { ru: 'переходов', en: 'visits' },
  'word.message1': { ru: 'сообщение', en: 'message' },
  'word.message2': { ru: 'сообщения', en: 'messages' },
  'word.message5': { ru: 'сообщений', en: 'messages' },
  'word.reply1': { ru: 'ответ', en: 'reply' },
  'word.reply2': { ru: 'ответа', en: 'replies' },
  'word.reply5': { ru: 'ответов', en: 'replies' },
  'word.new1': { ru: 'новое', en: 'new' },
  'word.new2': { ru: 'новых', en: 'new' },
  'word.new5': { ru: 'новых', en: 'new' },

  'home.today': { ru: 'Сегодня {visits} и {messages}', en: 'Today: {visits} and {messages}' },
  'home.title': { ru: 'Твоя анонка', en: 'Your Anonka' },
  'home.link.label': { ru: 'Твоя ссылка', en: 'Your link' },
  'home.prompt.label': { ru: 'Вопрос на ссылке', en: 'Question on your link' },
  'home.prompt.fallback': { ru: 'Напиши мне анонимно', en: 'Message me anonymously' },
  'home.total.visits': { ru: 'переходов', en: 'visits' },
  'home.total.messages': { ru: 'сообщений', en: 'messages' },
  'home.total.replies': { ru: 'ответов', en: 'replies' },
  'home.card.inbox': { ru: 'Входящие', en: 'Inbox' },
  'home.card.inbox.note': { ru: 'Всё, что тебе написали', en: 'Everything people sent you' },
  'home.card.inbox.unread': { ru: '{n} {word}, открывай', en: '{n} {word}, go look' },
  'home.card.story': { ru: 'В сторис', en: 'Story' },
  'home.card.stats': { ru: 'Статистика', en: 'Stats' },
  'home.premium': { ru: 'Анонка Premium', en: 'Anonka Premium' },
  'home.premium.active': { ru: 'Premium включён', en: 'Premium is on' },
  'home.premium.note': { ru: 'Откуда пишут, графики и цвета', en: 'Where they write from, charts and colors' },
  'home.promise': { ru: 'Кто написал, мы не показываем никому. Даже за деньги.', en: 'We never show who wrote. Not even for money.' },

  'link.copy': { ru: 'Скопировать', en: 'Copy' },
  'link.share': { ru: 'Отправить', en: 'Send' },
  'link.copied': { ru: 'Ссылка скопирована', en: 'Link copied' },
  'share.text': { ru: 'Напиши мне анонимно, я не узнаю, кто это', en: "Message me anonymously, I won't know it's you" },

  'inbox.title': { ru: 'Входящие', en: 'Inbox' },
  'inbox.note.in': { ru: 'Отвечай тут или прямо в чате с ботом', en: 'Reply here or right in the bot chat' },
  'inbox.note.out': { ru: 'Твои анонимные сообщения и ответы на них', en: 'What you sent anonymously and the replies' },
  'inbox.tab.in': { ru: 'Мне пишут', en: 'To me' },
  'inbox.tab.out': { ru: 'Я пишу', en: 'From me' },
  'inbox.empty.title': { ru: 'Пока тихо', en: 'Quiet so far' },
  'inbox.empty.note': { ru: 'Кинь ссылку в сторис, обычно это работает', en: 'Drop your link in a story, that usually does it' },
  'inbox.empty.action': { ru: 'Сделать сторис', en: 'Make a story' },
  'inbox.emptyOut.title': { ru: 'Отправленных пока нет', en: "You haven't written to anyone" },
  'inbox.emptyOut.note': { ru: 'Открой чью-нибудь ссылку, и переписка появится тут', en: "Open someone's link and the chat shows up here" },
  'inbox.unread': { ru: 'не прочитано', en: 'unread' },
  'inbox.waiting': { ru: 'ждём ответ', en: 'waiting for a reply' },
  'inbox.more': { ru: 'Показать ещё', en: 'Show more' },
  'inbox.history': { ru: 'Тут последние {days} дней. Вся история без срока в Premium', en: 'Showing the last {days} days. Full history comes with Premium' },

  'kind.photo': { ru: 'Фото', en: 'Photo' },
  'kind.video': { ru: 'Видео', en: 'Video' },
  'kind.animation': { ru: 'Гифка', en: 'GIF' },
  'kind.voice': { ru: 'Голосовое', en: 'Voice' },
  'kind.video_note': { ru: 'Кружок', en: 'Video note' },
  'kind.sticker': { ru: 'Стикер', en: 'Sticker' },
  'kind.audio': { ru: 'Аудио', en: 'Audio' },

  'thread.title': { ru: 'Анонимное сообщение', en: 'Anonymous message' },
  'thread.titleOut': { ru: 'Твоё сообщение', en: 'Your message' },
  'thread.gone.title': { ru: 'Сообщение недоступно', en: 'Message unavailable' },
  'thread.gone.note': { ru: 'Возможно, его удалили или ссылка устарела', en: 'It may have been removed or the link is outdated' },
  'thread.inChat': { ru: 'смотри в чате', en: 'see it in the chat' },
  'thread.react': { ru: 'Реакция {emoji}', en: 'React {emoji}' },
  'thread.reacted': { ru: 'Реакция ушла', en: 'Reaction sent' },
  'thread.placeholder.owner': { ru: 'Ответ увидит только автор', en: 'Only the author sees the reply' },
  'thread.placeholder.author': { ru: 'Пиши, ты всё ещё аноним', en: "Write, you're still anonymous" },
  'thread.send': { ru: 'Отправить', en: 'Send' },
  'thread.waiting': { ru: 'Ответить можно, когда тебе напишут в ответ', en: 'You can reply once they answer you' },
  'thread.blockedNote': { ru: 'Переписка закрыта', en: 'This chat is closed' },
  'thread.menu': { ru: 'Действия', en: 'Actions' },
  'thread.block': { ru: 'Заблокировать', en: 'Block' },
  'thread.block.note': { ru: 'Больше не сможет тебе писать', en: "They won't be able to write to you" },
  'thread.unblock': { ru: 'Разблокировать', en: 'Unblock' },
  'thread.blocked': { ru: 'Заблокировано', en: 'Blocked' },
  'thread.unblocked': { ru: 'Разблокировано', en: 'Unblocked' },
  'thread.report': { ru: 'Пожаловаться', en: 'Report' },
  'thread.report.note': { ru: 'Угрозы, травля, спам. Посмотрим в течение суток', en: 'Threats, bullying, spam. We check within a day' },
  'thread.reported': { ru: 'Жалоба ушла', en: 'Report sent' },
  'thread.reportedAlready': { ru: 'Жалоба уже отправлена', en: 'Already reported' },
  'thread.hide': { ru: 'Убрать из входящих', en: 'Remove from inbox' },
  'thread.hide.note': { ru: 'В чате с ботом сообщение останется', en: 'It stays in the bot chat' },
  'thread.hidden': { ru: 'Убрано', en: 'Removed' },

  'stats.title': { ru: 'Статистика', en: 'Stats' },
  'stats.rank': { ru: 'По сообщениям ты в топ {percent}%', en: "By messages you're in the top {percent}%" },
  'stats.visits': { ru: 'Переходы', en: 'Visits' },
  'stats.messages': { ru: 'Сообщения', en: 'Messages' },
  'stats.week': { ru: 'за неделю', en: 'this week' },
  'stats.chart7': { ru: 'Последние 7 дней', en: 'Last 7 days' },
  'stats.chart30': { ru: 'Последние 30 дней', en: 'Last 30 days' },
  'stats.replies': { ru: 'твоих ответов: {n}', en: 'your replies: {n}' },
  'stats.sources': { ru: 'Откуда приходят', en: 'Where they come from' },
  'stats.sources.note': { ru: 'Поставь разные ссылки в разные соцсети, и тут будет видно, где тебя читают', en: 'Put a different link in each app and see where people find you' },
  'stats.sources.teaser': { ru: 'Отдельные ссылки для Instagram, TikTok, Telegram и VK покажут, откуда именно тебе пишут', en: 'Separate links for Instagram, TikTok, Telegram and VK show exactly where messages come from' },
  'stats.unlock': { ru: 'Открыть с Premium', en: 'Unlock with Premium' },
  'stats.direct': { ru: 'Обычная ссылка', en: 'Main link' },
  'stats.sourceLine': { ru: 'переходов {visits} · сообщений {messages}', en: '{visits} visits · {messages} messages' },
  'stats.copySource': { ru: 'Ссылка', en: 'Link' },
  'stats.sourceCopied': { ru: 'Ссылка для {source} скопирована', en: '{source} link copied' },

  'story.title': { ru: 'Сторис', en: 'Story' },
  'story.note': { ru: 'Карточка с твоей ссылкой', en: 'A card with your link' },
  'story.preview': { ru: 'Так будет выглядеть сторис', en: 'Story preview' },
  'story.colors': { ru: 'Цвет карточки', en: 'Card color' },
  'story.post': { ru: 'Выложить в сторис', en: 'Post to story' },
  'story.open': { ru: 'Открыть картинку', en: 'Open the image' },
  'story.widget': { ru: 'Напиши мне', en: 'Message me' },
  'story.hint': { ru: 'Кликабельная ссылка на сторис появится, если у тебя Telegram Premium. Адрес в любом случае есть на картинке', en: 'The clickable link sticker needs Telegram Premium. The address is on the image either way' },

  'theme.azure': { ru: 'Синий', en: 'Blue' },
  'theme.coral': { ru: 'Коралловый', en: 'Coral' },
  'theme.violet': { ru: 'Фиолетовый', en: 'Violet' },
  'theme.emerald': { ru: 'Зелёный', en: 'Green' },
  'theme.amber': { ru: 'Жёлтый', en: 'Amber' },
  'theme.ink': { ru: 'Тёмный', en: 'Dark' },

  'premium.title': { ru: 'Premium', en: 'Premium' },
  'premium.hero': { ru: 'Больше видно, больше пишут', en: 'See more, get more' },
  'premium.hero.active': { ru: 'Premium уже с тобой', en: 'Premium is on' },
  'premium.until': { ru: 'Работает до {date}', en: 'Active until {date}' },
  'premium.perk.sources': { ru: 'Метки для ссылок', en: 'Link tags' },
  'premium.perk.sources.note': { ru: 'Отдельные ссылки для Instagram, TikTok, Telegram и VK', en: 'Separate links for Instagram, TikTok, Telegram and VK' },
  'premium.perk.stats': { ru: 'Статистика за 30 дней', en: '30 day stats' },
  'premium.perk.stats.note': { ru: 'График переходов и сообщений по дням', en: 'Daily chart of visits and messages' },
  'premium.perk.themes': { ru: 'Шесть цветов для сторис', en: 'Six story colors' },
  'premium.perk.themes.note': { ru: 'Карточка под твою ленту', en: 'A card that fits your feed' },
  'premium.perk.history': { ru: 'История без срока', en: 'Full history' },
  'premium.perk.history.note': { ru: 'Все сообщения в приложении, а не только за 30 дней', en: 'Every message in the app, not only the last 30 days' },
  'premium.plans': { ru: 'Тариф', en: 'Plan' },
  'premium.plan.month': { ru: 'Месяц', en: 'Month' },
  'premium.plan.month.note': { ru: 'Продлевается сам, отменить можно в любой момент', en: 'Renews itself, cancel any time' },
  'premium.plan.year': { ru: 'Год', en: 'Year' },
  'premium.plan.year.note': { ru: 'Один платёж, без автопродления', en: 'One payment, no auto renewal' },
  'premium.thanks': { ru: 'Premium включён, спасибо', en: 'Premium is on, thank you' },
  'premium.consent.month': { ru: '{stars} ⭐ сразу и дальше каждые 30 дней, пока не отменишь. Отменить можно в любой момент здесь или в Telegram: Настройки, Мои звёзды, Подписки. После отмены Premium работает до конца оплаченного срока.', en: '{stars} ⭐ now and every 30 days until you cancel. Cancel any time here or in Telegram: Settings, My Stars, Subscriptions. After cancelling, Premium works until the paid period ends.' },
  'premium.consent.year': { ru: '{stars} ⭐ один раз, без автопродления.', en: '{stars} ⭐ once, no auto renewal.' },
  'premium.agree.month': { ru: 'Подписаться, {stars} ⭐ в месяц', en: 'Subscribe, {stars} ⭐ a month' },
  'premium.agree.year': { ru: 'Оплатить {stars} ⭐', en: 'Pay {stars} ⭐' },
  'premium.cancel': { ru: 'Отменить автопродление', en: 'Cancel auto renewal' },
  'premium.cancelled': { ru: 'Автопродление выключено, Premium работает до конца срока', en: 'Auto renewal is off, Premium works until the period ends' },
  'premium.nothing': { ru: 'Активной подписки нет', en: 'No active subscription' },
  'premium.honest': { ru: 'Имя автора Premium не показывает. Анонимность не продаётся.', en: 'Premium never reveals who wrote. Anonymity is not for sale.' },

  'settings.title': { ru: 'Настройки', en: 'Settings' },
  'settings.group.link': { ru: 'Ссылка', en: 'Link' },
  'settings.group.messages': { ru: 'Сообщения', en: 'Messages' },
  'settings.group.app': { ru: 'Приложение', en: 'App' },
  'settings.nick': { ru: 'Свой адрес ссылки', en: 'Custom link' },
  'settings.nick.none': { ru: 'Сейчас случайный', en: 'Random for now' },
  'settings.nick.title': { ru: 'Свой адрес', en: 'Custom address' },
  'settings.nick.hint': { ru: 'Будет t.me/{bot}?start=твой_адрес. Латиница, цифры и _, от 4 до 24 символов', en: 'It becomes t.me/{bot}?start=your_name. Latin letters, digits and _, 4 to 24 characters' },
  'settings.prompt': { ru: 'Вопрос на ссылке', en: 'Link question' },
  'settings.prompt.none': { ru: 'Не задан', en: 'Not set' },
  'settings.prompt.title': { ru: 'Вопрос на ссылке', en: 'Link question' },
  'settings.prompt.hint': { ru: 'Его увидит каждый, кто откроет ссылку. Отлично заходят игры вроде «норм или стрём»', en: 'Everyone who opens your link sees it. Games like "rate my outfit" work great' },
  'settings.prompt.placeholder': { ru: 'норм или стрём мой новый цвет волос?', en: 'rate my new hair color?' },
  'settings.prompt.clear': { ru: 'Убрать вопрос', en: 'Remove question' },
  'settings.reset': { ru: 'Новая ссылка', en: 'New link' },
  'settings.reset.note': { ru: 'Если старую увидели не те люди', en: 'If the wrong people saw the old one' },
  'settings.reset.title': { ru: 'Новая ссылка', en: 'New link' },
  'settings.reset.confirm': { ru: 'Старая ссылка перестанет работать, свой адрес тоже сбросится. Переписки останутся.', en: 'The old link stops working and your custom address is cleared. Your chats stay.' },
  'settings.reset.yes': { ru: 'Да, обновить', en: 'Yes, update' },
  'settings.reset.done': { ru: 'Ссылка обновлена', en: 'Link updated' },
  'settings.receive': { ru: 'Принимать сообщения', en: 'Take messages' },
  'settings.receive.note': { ru: 'Выключи, если нужна пауза', en: 'Turn off when you need a break' },
  'settings.media': { ru: 'Фото, видео и голосовые', en: 'Photos, videos and voice' },
  'settings.media.note': { ru: 'Иначе только текст', en: 'Otherwise text only' },
  'settings.links': { ru: 'Ссылки в сообщениях', en: 'Links in messages' },
  'settings.links.note': { ru: 'Лучше не включать, так меньше спама', en: 'Better off, less spam that way' },
  'settings.filter': { ru: 'Фильтр грубости', en: 'Rudeness filter' },
  'settings.filter.note': { ru: 'Мат и оскорбления не долетят', en: "Swearing and insults won't get through" },
  'settings.silent': { ru: 'Без звука', en: 'Silent' },
  'settings.silent.note': { ru: 'Уведомления придут тихо', en: 'Notifications arrive quietly' },
  'settings.promise': { ru: 'Угрозы и призывы навредить себе не доходят никогда, отправителя ждёт бан', en: 'Threats and pushing someone to self-harm never get through, and the sender gets banned' },
  'settings.language': { ru: 'Язык', en: 'Language' },
  'settings.theme': { ru: 'Оформление', en: 'Appearance' },
  'settings.theme.system': { ru: 'Авто', en: 'Auto' },
  'settings.theme.light': { ru: 'Светлое', en: 'Light' },
  'settings.theme.dark': { ru: 'Тёмное', en: 'Dark' },
  'settings.premium': { ru: 'Анонка Premium', en: 'Anonka Premium' },
  'settings.premium.active': { ru: 'Premium включён', en: 'Premium is on' },
  'settings.privacy': { ru: 'Конфиденциальность', en: 'Privacy' },
  'settings.terms': { ru: 'Условия', en: 'Terms' },

  'settings.group.data': { ru: 'Данные и правила', en: 'Data and rules' },
  'settings.support': { ru: 'Поддержка', en: 'Support' },
  'settings.support.note': { ru: 'Напиши /support в чате с ботом', en: 'Send /support in the bot chat' },
  'settings.support.toast': { ru: 'Напиши боту /support и опиши вопрос', en: 'Send /support to the bot and describe the issue' },
  'settings.export': { ru: 'Скачать мои данные', en: 'Download my data' },
  'settings.export.note': { ru: 'Файл придёт в чат с ботом', en: 'The file arrives in the bot chat' },
  'settings.export.done': { ru: 'Файл отправлен в чат с ботом', en: 'The file is in the bot chat' },
  'settings.erase': { ru: 'Удалить все данные', en: 'Delete all data' },
  'settings.erase.note': { ru: 'Ссылка, переписки и статистика', en: 'Link, chats and stats' },
  'settings.erase.title': { ru: 'Удалить всё?', en: 'Delete everything?' },
  'settings.erase.confirm': { ru: 'Уйдут ссылка, настройки, статистика и все переписки с твоим участием, в том числе у собеседников. Отменить нельзя. Записи об оплате хранятся отдельно, этого требует закон.', en: 'Your link, settings, stats and every chat you took part in will be gone, including on the other side. This cannot be undone. Payment records are kept separately, as the law requires.' },
  'settings.erase.yes': { ru: 'Удалить навсегда', en: 'Delete forever' },
  'settings.safety': { ru: 'Безопасность и жалобы', en: 'Safety and reporting' },

  'report.title': { ru: 'Что не так?', en: "What's wrong?" },
  'report.harm': { ru: 'Угрозы или травля', en: 'Threats or bullying' },
  'report.intimate': { ru: 'Интимное без согласия', en: 'Intimate content without consent' },
  'report.child': { ru: 'Сексуальное с участием детей', en: 'Sexual content involving minors' },
  'report.spam': { ru: 'Спам или обман', en: 'Spam or scam' },
  'report.other': { ru: 'Другое', en: 'Something else' },
  'report.urgent.note': { ru: 'Уберём сразу, автор больше не сможет писать', en: 'Removed right away, the sender is blocked' },
  'thread.reportedRemoved': { ru: 'Убрали, автор больше не сможет тебе писать', en: "Removed, the sender can't write to you anymore" },

  'age.required.title': { ru: 'Сначала пара секунд в боте', en: 'One step in the bot first' },
  'age.required.note': { ru: 'Открой чат с ботом и ответь, сколько тебе лет. Потом возвращайся', en: 'Open the bot chat and tell us your age, then come back' },
  'age.required.action': { ru: 'В чат с ботом', en: 'To the bot chat' },
  'age.denied.title': { ru: 'Пока рано', en: 'Not yet' },
  'age.denied.note': { ru: 'Анонка доступна с 14 лет', en: 'Anonka is available from age 14' },

  'admin.title': { ru: 'Панель', en: 'Panel' },
  'admin.denied.title': { ru: 'Нет доступа', en: 'No access' },
  'admin.denied.note': { ru: 'Панель видят только владелец и админы', en: 'Only the owner and admins can see the panel' },
  'admin.role.owner': { ru: 'Владелец', en: 'Owner' },
  'admin.role.admin': { ru: 'Админ', en: 'Admin' },
  'admin.tab.reports': { ru: 'Жалобы', en: 'Reports' },
  'admin.tab.stats': { ru: 'Статистика', en: 'Stats' },
  'admin.tab.team': { ru: 'Люди', en: 'People' },
  'admin.tab.money': { ru: 'Деньги', en: 'Money' },
  'admin.tab.audit': { ru: 'Журнал', en: 'Log' },
  'admin.banned': { ru: 'в бане', en: 'banned' },
  'admin.strikes': { ru: 'страйков {n}', en: '{n} strikes' },
  'admin.empty': { ru: 'Пока нет данных', en: 'No data yet' },
  'admin.chartLabel': { ru: 'График', en: 'Chart' },

  'admin.reason.auto': { ru: 'Фильтр угроз', en: 'Threat filter' },
  'admin.reason.harm': { ru: 'Угрозы, травля', en: 'Threats, bullying' },
  'admin.reason.intimate': { ru: 'Интимное', en: 'Intimate' },
  'admin.reason.child': { ru: 'Дети', en: 'Minors' },
  'admin.reason.spam': { ru: 'Спам', en: 'Spam' },
  'admin.reason.other': { ru: 'Другое', en: 'Other' },
  'admin.status.open': { ru: 'Открыта', en: 'Open' },
  'admin.status.banned': { ru: 'Бан', en: 'Banned' },
  'admin.status.strike': { ru: 'Страйк', en: 'Strike' },
  'admin.status.dismissed': { ru: 'Отклонена', en: 'Dismissed' },

  'admin.reports.open': { ru: 'Открытые {n}', en: 'Open {n}' },
  'admin.reports.closed': { ru: 'Закрытые {n}', en: 'Closed {n}' },
  'admin.reports.all': { ru: 'Все', en: 'All' },
  'admin.reports.anyReason': { ru: 'Любая причина', en: 'Any reason' },
  'admin.reports.empty.title': { ru: 'Жалоб нет', en: 'No reports' },
  'admin.reports.empty.note': { ru: 'Когда кто-то пожалуется, жалоба появится тут и придёт в чат', en: 'New reports show up here and in the chat' },

  'admin.report.title': { ru: 'Жалоба #{id}', en: 'Report #{id}' },
  'admin.report.gone': { ru: 'Жалобу удалили вместе с перепиской', en: 'The report was removed with its chat' },
  'admin.report.auto': { ru: 'Автоматически', en: 'Automatic' },
  'admin.report.handled': { ru: 'Разобрал {who}', en: 'Handled by {who}' },
  'admin.report.childNote': { ru: 'Медиа не показываем и не пересылаем. Если это материал с насилием над детьми, отправь отчёт в NCMEC по docs/SAFETY.md и не снимай legal hold', en: 'Media is never shown or forwarded. If this is child sexual abuse material, report it to NCMEC per docs/SAFETY.md and keep the legal hold' },
  'admin.report.intimateNote': { ru: 'Сообщение уже убрано у получателя. По закону на разбор 48 часов', en: 'Already removed from the recipient. The law gives 48 hours to act' },
  'admin.report.sender': { ru: 'Отправитель', en: 'Sender' },
  'admin.report.recipient': { ru: 'Получатель', en: 'Recipient' },
  'admin.report.senderShort': { ru: 'отправитель', en: 'sender' },
  'admin.report.recipientShort': { ru: 'получатель', en: 'recipient' },
  'admin.report.against': { ru: 'жалоб {n}', en: '{n} reports' },
  'admin.report.blockedBy': { ru: 'блоков {n}', en: '{n} blocks' },
  'admin.report.since': { ru: 'с {date}', en: 'since {date}' },
  'admin.report.thread': { ru: 'Переписка', en: 'Conversation' },
  'admin.report.replay': { ru: 'В чат 1 в 1', en: 'Send to chat' },
  'admin.report.replayed': { ru: 'Прислал в чат сообщений: {n}', en: 'Sent {n} messages to the chat' },
  'admin.report.inChat': { ru: 'полная версия в чате', en: 'full version in the chat' },
  'admin.report.held': { ru: 'под legal hold', en: 'under legal hold' },
  'admin.report.flagged': { ru: 'на это жалоба', en: 'reported' },
  'admin.report.removed': { ru: 'убрано', en: 'removed' },
  'admin.report.undelivered': { ru: 'не доставлено', en: 'not delivered' },
  'admin.report.tags': { ru: 'Теги и заметка', en: 'Tags and note' },
  'admin.report.customTag': { ru: 'свой тег', en: 'custom tag' },
  'admin.report.addTag': { ru: 'Добавить', en: 'Add' },
  'admin.report.note': { ru: 'Заметка для других админов', en: 'Note for other admins' },
  'admin.report.ban': { ru: 'Забанить отправителя', en: 'Ban the sender' },
  'admin.report.strike': { ru: 'Выдать страйк', en: 'Give a strike' },
  'admin.report.dismiss': { ru: 'Отклонить', en: 'Dismiss' },
  'admin.report.reopen': { ru: 'Открыть снова', en: 'Reopen' },
  'admin.report.history': { ru: 'Другие сообщения отправителя', en: "Sender's other messages" },
  'admin.report.historyNote': { ru: 'Последние 20, чтобы понять, разовое это или система', en: 'The last 20, to tell a one-off from a pattern' },
  'admin.report.alsoReported': { ru: 'тоже жалоба', en: 'also reported' },

  'admin.stats.days': { ru: '{n} дней', en: '{n} days' },
  'admin.kpi.users': { ru: 'люди', en: 'users' },
  'admin.kpi.today': { ru: 'сегодня', en: 'today' },
  'admin.kpi.owners': { ru: 'с ответами', en: 'receiving' },
  'admin.kpi.messages': { ru: 'сообщения', en: 'messages' },
  'admin.kpi.visits': { ru: 'переходы', en: 'visits' },
  'admin.kpi.replies': { ru: 'доля ответов', en: 'reply rate' },
  'admin.kpi.stars': { ru: 'звёзды', en: 'stars' },
  'admin.kpi.total': { ru: 'всего', en: 'total' },
  'admin.kpi.reports': { ru: 'жалобы открыты', en: 'open reports' },
  'admin.kpi.banned': { ru: 'в бане', en: 'banned' },
  'admin.chart.newUsers': { ru: 'Новые люди', en: 'New users' },
  'admin.chart.period': { ru: 'за период {n}', en: '{n} in period' },
  'admin.chart.active': { ru: 'Активные за день', en: 'Daily active' },
  'admin.chart.messages': { ru: 'Анонимные сообщения', en: 'Anonymous messages' },
  'admin.chart.senders': { ru: 'писали {n} человек', en: '{n} people wrote' },
  'admin.chart.visits': { ru: 'Переходы по ссылкам', en: 'Link visits' },
  'admin.chart.stars': { ru: 'Звёзды', en: 'Stars' },
  'admin.chart.purchases': { ru: 'покупок {n}, возвратов {r}', en: '{n} purchases, {r} refunds' },
  'admin.chart.reports': { ru: 'Жалобы', en: 'Reports' },
  'admin.chart.hours': { ru: 'Сообщения по часам', en: 'Messages by hour' },
  'admin.chart.heat': { ru: 'Когда пишут', en: 'When people write' },
  'admin.chart.sources': { ru: 'Откуда переходят', en: 'Where visits come from' },
  'admin.chart.kinds': { ru: 'Что присылают', en: 'What people send' },
  'admin.chart.reasons': { ru: 'Причины жалоб', en: 'Report reasons' },
  'admin.chart.plans': { ru: 'Тарифы', en: 'Plans' },
  'admin.kind.text': { ru: 'Текст', en: 'Text' },

  'admin.user.title': { ru: 'Найти человека', en: 'Find a person' },
  'admin.user.find': { ru: 'Найти', en: 'Find' },
  'admin.user.none': { ru: 'Такого нет', en: 'Not found' },
  'admin.user.joined': { ru: 'С нами с {date}, был {seen}', en: 'Joined {date}, seen {seen}' },
  'admin.user.counts': { ru: 'получил {received}, отправил {sent}, ответил {replies}, переходов {visits}', en: 'received {received}, sent {sent}, replied {replies}, visits {visits}' },
  'admin.user.safety': { ru: 'страйков {strikes}, жалоб на него {reports}', en: '{strikes} strikes, {reports} reports against' },
  'admin.user.premium': { ru: 'Premium до {date}', en: 'Premium until {date}' },
  'admin.user.free': { ru: 'Без Premium', en: 'No Premium' },
  'admin.user.ban': { ru: 'Забанить', en: 'Ban' },
  'admin.user.unban': { ru: 'Разбанить', en: 'Unban' },
  'admin.user.bannedDone': { ru: 'Забанен', en: 'Banned' },
  'admin.user.unbanned': { ru: 'Разбанен', en: 'Unbanned' },
  'admin.user.grant': { ru: '+30 дней Premium', en: '+30 days Premium' },
  'admin.user.granted': { ru: 'Premium выдан', en: 'Premium granted' },
  'admin.team.title': { ru: 'Команда', en: 'Team' },
  'admin.team.note': { ru: 'Админы видят только жалобы и разбирают их. Статистика, люди, деньги и журнал только у владельца', en: 'Admins only see and handle reports. Stats, people, money and the log are owner only' },
  'admin.team.make': { ru: 'Сделать админом', en: 'Make admin' },
  'admin.team.add': { ru: 'Добавить', en: 'Add' },
  'admin.team.added': { ru: 'Админ добавлен', en: 'Admin added' },
  'admin.team.remove': { ru: 'Убрать', en: 'Remove' },
  'admin.team.removed': { ru: 'Больше не админ', en: 'No longer an admin' },
  'admin.money.empty': { ru: 'Оплат пока нет', en: 'No payments yet' },
  'admin.money.emptyNote': { ru: 'Покупки Premium появятся тут', en: 'Premium purchases show up here' },
  'admin.money.recurring': { ru: 'подписка', en: 'subscription' },
  'admin.money.refund': { ru: 'Вернуть', en: 'Refund' },
  'admin.money.refunded': { ru: 'Звёзды вернули', en: 'Stars refunded' },
  'admin.money.refundedLabel': { ru: 'возвращено', en: 'refunded' },

  'age.group.u12': { ru: 'до 13', en: 'under 13' },
  'age.group.13': { ru: '13', en: '13' },
  'age.group.14': { ru: '14–15', en: '14–15' },
  'age.group.16': { ru: '16–17', en: '16–17' },
  'age.group.18': { ru: '18+', en: '18+' },
  'weekday.0': { ru: 'вс', en: 'Su' },
  'weekday.1': { ru: 'пн', en: 'Mo' },
  'weekday.2': { ru: 'вт', en: 'Tu' },
  'weekday.3': { ru: 'ср', en: 'We' },
  'weekday.4': { ru: 'чт', en: 'Th' },
  'weekday.5': { ru: 'пт', en: 'Fr' },
  'weekday.6': { ru: 'сб', en: 'Sa' },

  'nick.format': { ru: 'Только латиница, цифры и _, от 4 до 24 символов', en: 'Latin letters, digits and _ only, 4 to 24 characters' },
  'nick.reserved': { ru: 'Этот адрес занят системой, попробуй другой', en: 'That address is reserved, try another one' },
  'nick.taken': { ru: 'Этот адрес уже кто-то забрал', en: 'Someone already took that one' },

  'reject.self': { ru: 'Себе написать не получится', en: "You can't message yourself" },
  'reject.paused': { ru: 'Этот человек пока не принимает сообщения', en: "This person isn't taking messages right now" },
  'reject.blocked': { ru: 'Переписка закрыта', en: 'This chat is closed' },
  'reject.media_off': { ru: 'Тут принимают только текст', en: 'Only text is accepted here' },
  'reject.links_off': { ru: 'Ссылки получатель отключил', en: "The recipient doesn't accept links" },
  'reject.rude': { ru: 'У получателя включён фильтр грубости. Перефразируй', en: 'The recipient has a rudeness filter on. Rephrase it' },
  'reject.severe': { ru: 'Такое не отправится. Угрозы тут под запретом', en: "This won't be sent. Threats are not allowed" },
  'reject.too_long': { ru: 'Длинновато, сократи', en: 'Too long, shorten it' },
  'reject.unsupported': { ru: 'Такой формат не дойдёт', en: "That format won't go through" },
  'reject.empty': { ru: 'Пустое сообщение не отправится', en: "An empty message can't be sent" },
  'reject.rate': { ru: 'Слишком часто, подожди пару минут', en: 'Too fast, give it a couple of minutes' },
  'reject.pair': { ru: 'Сообщений уже много, дай время ответить', en: "That's a lot of messages, give them time" },
  'reject.unreachable': { ru: 'Не доставлено: человек остановил бота', en: 'Not delivered: they stopped the bot' },
  'reject.banned': { ru: 'Аккаунт заблокирован за нарушения', en: 'The account was banned for violations' },
  'reject.gone': { ru: 'Сообщение уже недоступно', en: 'This message is no longer available' },
  'reject.nothing_to_reply': { ru: 'Пока не на что отвечать', en: 'Nothing to reply to yet' },
  'reject.premium': { ru: 'Это доступно с Premium', en: 'This comes with Premium' },
  'reject.prompt_long': { ru: 'Вопрос длинноват, до 140 символов', en: 'The question is too long, 140 characters max' },
} as const;

export type StringKey = keyof typeof STRINGS;
